---
- name: Install Aerospike on Ubuntu 24.04
  hosts: all
  become: yes
  tasks:
    - name: Update the apt cache
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name:
          - wget
          - lsb-release
        state: present

    - name: Download Aerospike package
      shell: |
        wget -O /tmp/aerospike.tgz https://download.aerospike.com/artifacts/aerospike-server-community/8.0.0/aerospike-server-community_8.0.0.0-rc3_tools-11.1.1_ubuntu24.04_x86_64.tgz
      args:
        creates: /tmp/aerospike.tgz

    - name: Extract Aerospike package
      unarchive:
        src: /tmp/aerospike.tgz
        dest: /tmp/aerospike
        remote_src: yes

    - name: Install Aerospike
      shell: |
        cd /tmp/aerospike && sudo ./asinstall
      args:
        chdir: /tmp/aerospike

    - name: Verify Aerospike installation
      command: asd --version
      register: aerospike_version
      ignore_errors: yes

    - name: Debug Aerospike version
      debug:
        msg: "Aerospike version installed: {{ aerospike_version.stdout }}"
